Script started on 西元2022年01月26日 (週三) 04時20分21秒
]0;chungmop@zuma:hw2[chungmop@zuma hw2]$ gcc PhotoLab.c -std=c11 -Wall -o PhotoLab
]0;chungmop@zuma:hw2[chungmop@zuma hw2]$ ./PhotoLab
---------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 1
Please input the file name to load: EngPlaza
EngPlaza.ppm was read successfully!
---------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 11
EngPlaza.ppm was read successfully!
"Black and White" Operation is done!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

EngPlaza.ppm was read successfully!
"Negative" Operation is done!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

EngPlaza.ppm was read successfully!
"ColorFilter" Operation is done!
colorfilter.ppm was saved successfully. 
colorfilter.jpg was stored for viewing. 
Color Filter tested!

EngPlaza.ppm was read successfully!
"Edge" Operation is done!
edge.ppm was saved successfully. 
edge.jpg was stored for viewing. 
Edge Detection tested!

EngPlaza.ppm was read successfully!
"Shuffle" Operation is done!
shuffle.ppm was saved successfully. 
shuffle.jpg was stored for viewing. 
Shuffle tested!

EngPlaza.ppm was read successfully!
"VFlip" Operation is done!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
Vertical Flip tested!

EngPlaza.ppm was read successfully!
"VMirror" Operation is done!
vmirror.ppm was saved successfully. 
vmirror.jpg was stored for viewing. 
Vertical Mirroring tested!

EngPlaza.ppm was read successfully!
"Border" Operation is done!
border.ppm was saved successfully. 
border.jpg was stored for viewing. 
Border tested!

---------------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Make a negative of an image
5: Color filter an image
6: Sketch the edge of an image
7: Shuffle an image
8: Flip an image vertically
9: Mirror an image vertically
10: Add Border to an image
11: Test all functions
12: Exit
please make your choice: 12
Exiting program... Bye!
]0;chungmop@zuma:hw2[chungmop@zuma hw2]$ exit
exit

Script done on 西元2022年01月26日 (週三) 04時21分49秒
