Script started on 西元2022年02月09日 (週三) 05時21分48秒
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ make clean
make[2]: Entering directory '/users/ugrad/chungmop/eecs22/hw3'
rm -f *.o
rm -f PhotoLab 
rm -f PhotoLabTest
make[2]: Leaving directory '/users/ugrad/chungmop/eecs22/hw3'
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ make PhotoLab
make[2]: Entering directory '/users/ugrad/chungmop/eecs22/hw3'
gcc -c FileIO.c -o FileIO.o -std=c11 -Wall
gcc -c DIPs.c -o DIPs.o -std=c11 -Wall
gcc -c Advanced.c -o Advanced.o -std=c11 -Wall
gcc -c PhotoLab.c -o PhotoLab.o -std=c11 -Wall
[01m[KPhotoLab.c:[m[K In function ‘[01m[Kmain[m[K’:
[01m[KPhotoLab.c:64:49:[m[K [01;35m[Kwarning: [m[Kimplicit declaration of function ‘[01m[KBlackNWhite[m[K’ [[01;35m[K-Wimplicit-function-declaration[m[K]
                                                 [01;35m[KBlackNWhite[m[K(R, G, B);
                                                 [01;35m[K^~~~~~~~~~~[m[K
ar rc libfilter.a DIPs.o Advanced.o 
ranlib libfilter.a
gcc -Wall PhotoLab.o FileIO.o -L. -lfilter -lm -o PhotoLab
make[2]: Leaving directory '/users/ugrad/chungmop/eecs22/hw3'
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ ./PhotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
 10: Add border to an image
 11: Add noise to an image
 12: Sharpen an image
 13: Posterize an image
 14: Motion Blur
 15: Test all function
 16: Exit
Please make your choice: 1 1
Please input the file name to load: EngPlaza
EngPlaza.ppm was read.

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
 10: Add border to an image
 11: Add noise to an image
 12: Sharpen an image
 13: Posterize an image
 14: Motion Blur
 15: Test all function
 16: Exit
Please make your choice: 15
EngPlaza.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black & White tested!

EngPlaza.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

EngPlaza.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

EngPlaza.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge Detection tested!

EngPlaza.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

EngPlaza.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

EngPlaza.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

EngPlaza.ppm was read.
border.ppm was saved. 
border.jpg was stored.
Border tested!

EngPlaza.ppm was read.
nosie.ppm was saved. 
nosie.jpg was stored.
Noise tested!

EngPlaza.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
Sharpen tested!

EngPlaza.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
Posterize tested!

EngPlaza.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.
MotionBlur tested!

Exiting program...Bye!
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ make PhotoLabTest
make[2]: Entering directory '/users/ugrad/chungmop/eecs22/hw3'
gcc -c FileIO.c -o FileIO.o -std=c11 -Wall
gcc -c DIPs.c -o DIPs.o -std=c11 -Wall
gcc -c Advanced.c -o Advanced.o -std=c11 -Wall
gcc -c PhotoLab.c -o PhotoLabTest.o -DDEBUG -std=c11 -Wall
[01m[KPhotoLab.c:[m[K In function ‘[01m[Kmain[m[K’:
[01m[KPhotoLab.c:64:49:[m[K [01;35m[Kwarning: [m[Kimplicit declaration of function ‘[01m[KBlackNWhite[m[K’ [[01;35m[K-Wimplicit-function-declaration[m[K]
                                                 [01;35m[KBlackNWhite[m[K(R, G, B);
                                                 [01;35m[K^~~~~~~~~~~[m[K
ar rc libfilter.a DIPs.o Advanced.o
ranlib libfilter.a
gcc -Wall PhotoLabTest.o FileIO.o -L. -lfilter -lm -o PhotoLabTest
make[2]: Leaving directory '/users/ugrad/chungmop/eecs22/hw3'
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ ./PhotoLabTest
Debugging...
EngPlaza.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
Black & White tested!

EngPlaza.ppm was read.
negative.ppm was saved. 
negative.jpg was stored.
Negative tested!

EngPlaza.ppm was read.
colorfilter.ppm was saved. 
colorfilter.jpg was stored.
Color Filter tested!

EngPlaza.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
Edge Detection tested!

EngPlaza.ppm was read.
vmirror.ppm was saved. 
vmirror.jpg was stored.
VMirror tested!

EngPlaza.ppm was read.
vflip.ppm was saved. 
vflip.jpg was stored.
VFlip tested!

EngPlaza.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
Shuffle tested!

EngPlaza.ppm was read.
border.ppm was saved. 
border.jpg was stored.
Border tested!

EngPlaza.ppm was read.
nosie.ppm was saved. 
nosie.jpg was stored.
Noise tested!

EngPlaza.ppm was read.
sharpen.ppm was saved. 
sharpen.jpg was stored.
Sharpen tested!

EngPlaza.ppm was read.
posterize.ppm was saved. 
posterize.jpg was stored.
Posterize tested!

EngPlaza.ppm was read.
blur.ppm was saved. 
blur.jpg was stored.
MotionBlur tested!

]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ touch Advanced.c
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ make PhotoLab
make[2]: Entering directory '/users/ugrad/chungmop/eecs22/hw3'
gcc -c FileIO.c -o FileIO.o -std=c11 -Wall
gcc -c DIPs.c -o DIPs.o -std=c11 -Wall
gcc -c Advanced.c -o Advanced.o -std=c11 -Wall
gcc -c PhotoLab.c -o PhotoLab.o -std=c11 -Wall
[01m[KPhotoLab.c:[m[K In function ‘[01m[Kmain[m[K’:
[01m[KPhotoLab.c:64:49:[m[K [01;35m[Kwarning: [m[Kimplicit declaration of function ‘[01m[KBlackNWhite[m[K’ [[01;35m[K-Wimplicit-function-declaration[m[K]
                                                 [01;35m[KBlackNWhite[m[K(R, G, B);
                                                 [01;35m[K^~~~~~~~~~~[m[K
ar rc libfilter.a DIPs.o Advanced.o 
ranlib libfilter.a
gcc -Wall PhotoLab.o FileIO.o -L. -lfilter -lm -o PhotoLab
make[2]: Leaving directory '/users/ugrad/chungmop/eecs22/hw3'
]0;chungmop@zuma:hw3[chungmop@zuma hw3]$ exit
exit

Script done on 西元2022年02月09日 (週三) 05時25分21秒
