Script started on 西元2022年02月23日 (週三) 06時00分19秒
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ make 
gcc -Wall -std=c11 -c Image.c -o Image.o
gcc -Wall -std=c11 -c Test.c -o Test.o
gcc -Wall -std=c11 -c PhotoLab.c -o PhotoLab.o
[01m[KPhotoLab.c:[m[K In function ‘[01m[Kmain[m[K’:
[01m[KPhotoLab.c:31:6:[m[K [01;35m[Kwarning: [m[Kvariable ‘[01m[Kbug[m[K’ set but not used [[01;35m[K-Wunused-but-set-variable[m[K]
  int [01;35m[Kbug[m[K;
      [01;35m[K^~~[m[K
gcc -Wall -std=c11 -c FileIO.c -o FileIO.o
gcc -Wall -std=c11 -c DIPs.c -o DIPs.o
[01m[KDIPs.c:[m[K In function ‘[01m[KAddBorder[m[K’:
[01m[KDIPs.c:259:3:[m[K [01;35m[Kwarning: [m[K‘[01m[Kreturn[m[K’ with no value, in function returning non-void
   [01;35m[Kreturn[m[K;
   [01;35m[K^~~~~~[m[K
[01m[KDIPs.c:216:8:[m[K [01;36m[Knote: [m[Kdeclared here
 IMAGE *[01;36m[KAddBorder[m[K(IMAGE *image, char color[SLEN], int border_width) {
        [01;36m[K^~~~~~~~~[m[K
gcc -Wall -std=c11 -c Advanced.c -o Advanced.o
[01m[KAdvanced.c:[m[K In function ‘[01m[KWatermark[m[K’:
[01m[KAdvanced.c:264:12:[m[K [01;35m[Kwarning: [m[Kreturn discards ‘[01m[Kconst[m[K’ qualifier from pointer target type [[01;35m[K-Wdiscarded-qualifiers[m[K]
     return [01;35m[Kwatermark_image[m[K;
            [01;35m[K^~~~~~~~~~~~~~~[m[K
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -Wall PhotoLab.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLab
gcc -Wall -std=c11 -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
[01m[KPhotoLab.c:[m[K In function ‘[01m[Kmain[m[K’:
[01m[KPhotoLab.c:31:6:[m[K [01;35m[Kwarning: [m[Kvariable ‘[01m[Kbug[m[K’ set but not used [[01;35m[K-Wunused-but-set-variable[m[K]
  int [01;35m[Kbug[m[K;
      [01;35m[K^~~[m[K
[01m[KPhotoLab.c:30:6:[m[K [01;35m[Kwarning: [m[Kvariable ‘[01m[Krc[m[K’ set but not used [[01;35m[K-Wunused-but-set-variable[m[K]
  int [01;35m[Krc[m[K ;
      [01;35m[K^~[m[K
gcc -Wall PhotoLab_DEBUG.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLabTest
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ ./Pht[KotoLab

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Add Motion Blur to an image
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast of an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19
Empty JPEG image (DNL not supported)
*** glibc detected *** ./PhotoLab: double free or corruption (fasttop): 0x0000000002427280 ***
======= Backtrace: =========
/lib64/libc.so.6[0x32e0875e6e]
/lib64/libc.so.6[0x32e0878cbd]
./PhotoLab[0x401980]
./PhotoLab[0x402538]
./PhotoLab[0x401279]
/lib64/libc.so.6(__libc_start_main+0x100)[0x32e081ed20]
./PhotoLab[0x400a49]
======= Memory map: ========
00400000-00407000 r-xp 00000000 00:1f 9189678281                         /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLab
00606000-00607000 r--p 00006000 00:1f 9189678281                         /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLab
00607000-00608000 rw-p 00007000 00:1f 9189678281                         /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLab
023ee000-0243b000 rw-p 00000000 00:00 0                                  [heap]
32e0400000-32e0420000 r-xp 00000000 08:01 3015019                        /lib64/ld-2.12.so
32e0620000-32e0621000 r--p 00020000 08:01 3015019                        /lib64/ld-2.12.so
32e0621000-32e0622000 rw-p 00021000 08:01 3015019                        /lib64/ld-2.12.so
32e0622000-32e0623000 rw-p 00000000 00:00 0 
32e0800000-32e098b000 r-xp 00000000 08:01 3015061                        /lib64/libc-2.12.so
32e098b000-32e0b8a000 ---p 0018b000 08:01 3015061                        /lib64/libc-2.12.so
32e0b8a000-32e0b8e000 r--p 0018a000 08:01 3015061                        /lib64/libc-2.12.so
32e0b8e000-32e0b90000 rw-p 0018e000 08:01 3015061                        /lib64/libc-2.12.so
32e0b90000-32e0b94000 rw-p 00000000 00:00 0 
32e6000000-32e6016000 r-xp 00000000 08:01 3017341                        /lib64/libgcc_s-4.4.7-20120601.so.1
32e6016000-32e6215000 ---p 00016000 08:01 3017341                        /lib64/libgcc_s-4.4.7-20120601.so.1
32e6215000-32e6216000 rw-p 00015000 08:01 3017341                        /lib64/libgcc_s-4.4.7-20120601.so.1
7fdeb4000000-7fdeb4021000 rw-p 00000000 00:00 0 
7fdeb4021000-7fdeb8000000 ---p 00000000 00:00 0 
7fdeb8f74000-7fdeb9094000 rw-p 00000000 00:00 0 
7fdeb9114000-7fdeb9865000 rw-p 00000000 00:00 0 
7fdeb987d000-7fdeb98e8000 rw-p 00000000 00:00 0 
7fdeb98ea000-7fdeb990f000 rw-p 00000000 00:00 0 
7ffe228d9000-7ffe22949000 rw-p 00000000 00:00 0                          [stack]
7ffe2298a000-7ffe2298b000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Abort (core dumped)
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ valgrind --leak-check=full PhotoLabTest
valgrind: PhotoLabTest: command not found
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ valgrind --leak-check=full PhotoLabTest [1@.[1@/PhotoLabTest
==10393== Memcheck, a memory error detector
==10393== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10393== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==10393== Command: ./PhotoLabTest
==10393== 
==10393== Syscall param write(buf) points to uninitialised byte(s)
==10393==    at 0x32E08DB860: __write_nocancel (in /lib64/libc-2.12.so)
==10393==    by 0x32E08719C2: _IO_file_write@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E0872F74: _IO_do_write@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E087274F: _IO_file_close_it@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E08663E7: fclose@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x401023: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40149E: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x503a00f is in a rw- anonymous segment
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x40363C: ColorFilter (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40158A: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x403DD6: Edge (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401606: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x403E0A: Edge (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401606: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x402578: Sharpen (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4018EA: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x4025AC: Sharpen (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4018EA: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x32E08721BB: _IO_file_overflow@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E086E696: fputc (in /lib64/libc-2.12.so)
==10393==    by 0x400FE0: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B9B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Syscall param write(buf) points to uninitialised byte(s)
==10393==    at 0x32E08DB860: __write_nocancel (in /lib64/libc-2.12.so)
==10393==    by 0x32E08719C2: _IO_file_write@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E0872F74: _IO_do_write@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E0872372: _IO_file_overflow@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E086E696: fputc (in /lib64/libc-2.12.so)
==10393==    by 0x400FE0: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B9B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x503a00f is in a rw- anonymous segment
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x32E08721E3: _IO_file_overflow@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E086E696: fputc (in /lib64/libc-2.12.so)
==10393==    by 0x400FE0: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B9B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x32E08721BB: _IO_file_overflow@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E086E696: fputc (in /lib64/libc-2.12.so)
==10393==    by 0x400FB8: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B9B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x32E08721E3: _IO_file_overflow@@GLIBC_2.2.5 (in /lib64/libc-2.12.so)
==10393==    by 0x32E086E696: fputc (in /lib64/libc-2.12.so)
==10393==    by 0x400FB8: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B9B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x4031A5: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x4031C8: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x403228: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x40324B: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x4032AB: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Conditional jump or move depends on uninitialised value(s)
==10393==    at 0x4032CE: BrightnessAndContrast (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BF7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 4
==10393==    at 0x4012E4: ImageWidth (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400E78: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b0 is 0 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 4
==10393==    at 0x4012F4: ImageHeight (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400E8A: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b4 is 4 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 8
==10393==    at 0x40114B: GetPixelR (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400F7F: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b8 is 8 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 4
==10393==    at 0x4012E4: ImageWidth (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40115A: GetPixelR (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400F7F: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b0 is 0 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 8
==10393==    at 0x40118C: GetPixelG (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400FA7: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365c0 is 16 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 4
==10393==    at 0x4012E4: ImageWidth (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40119B: GetPixelG (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400FA7: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b0 is 0 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 8
==10393==    at 0x4011CD: GetPixelB (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400FCF: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365c8 is 24 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid read of size 4
==10393==    at 0x4012E4: ImageWidth (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4011DC: GetPixelB (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400FCF: SaveImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CCE: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b0 is 0 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== Invalid free() / delete / delete[] / realloc()
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CE8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Address 0x50365b0 is 0 bytes inside a block of size 32 free'd
==10393==    at 0x4A07B92: free (vg_replace_malloc.c:529)
==10393==    by 0x401130: DeleteImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401CA7: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==  Block was alloc'd at
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 
==10393== HEAP SUMMARY:
==10393==     in use at exit: 9,433,313 bytes in 64 blocks
==10393==   total heap usage: 119 allocs, 56 frees, 9,453,833 bytes allocated
==10393== 
==10393== 25,000 bytes in 1 blocks are definitely lost in loss record 1 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402B35: Crop (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A7B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 25,000 bytes in 1 blocks are definitely lost in loss record 2 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402B35: Crop (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A7B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 25,000 bytes in 1 blocks are definitely lost in loss record 3 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402B35: Crop (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A7B: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 52,804 bytes in 1 blocks are definitely lost in loss record 4 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402DF8: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AF8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 52,804 bytes in 1 blocks are definitely lost in loss record 5 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402DF8: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AF8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 52,804 bytes in 1 blocks are definitely lost in loss record 6 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402DF8: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AF8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 134,441 bytes in 1 blocks are definitely lost in loss record 7 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 134,441 bytes in 1 blocks are definitely lost in loss record 8 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 13 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401457: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 14 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401457: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 15 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4014CF: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 16 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4014CF: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 17 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4014CF: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 18 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401547: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 19 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401547: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 20 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401547: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 21 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4015E5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 22 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4015E5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 23 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4015E5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 24 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40165D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 25 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40165D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 26 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40165D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 27 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4016D5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 28 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4016D5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 29 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4016D5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 30 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40174D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 31 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40174D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 32 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40174D: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 33 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4017C5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 34 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4017C5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 35 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4017C5: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 36 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40184C: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 37 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40184C: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 38 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x40184C: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 39 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4018C9: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 40 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4018C9: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 41 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4018C9: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 42 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401941: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 43 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401941: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 44 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401941: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 45 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4019C8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 46 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4019C8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 47 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x4019C8: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 48 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A45: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 49 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A45: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 50 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401A45: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 51 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AD2: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 52 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AD2: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 53 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401AD2: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 54 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B4F: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 55 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B4F: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 56 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B4F: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 57 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BCC: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 58 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BCC: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 147,456 bytes in 1 blocks are definitely lost in loss record 59 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401BCC: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 281,897 (134,441 direct, 147,456 indirect) bytes in 1 blocks are definitely lost in loss record 60 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C72: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 425,430 bytes in 1 blocks are definitely lost in loss record 61 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x40109A: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402CD1: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B75: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 425,430 bytes in 1 blocks are definitely lost in loss record 62 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010B7: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402CD1: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B75: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 425,430 bytes in 1 blocks are definitely lost in loss record 63 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x4010D4: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x402CD1: Resize (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401B75: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== 442,400 (32 direct, 442,368 indirect) bytes in 1 blocks are definitely lost in loss record 64 of 64
==10393==    at 0x4A081B8: malloc (vg_replace_malloc.c:298)
==10393==    by 0x401084: CreateImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400D20: LoadImage (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x401C4E: AutoTest (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393==    by 0x400A93: main (in /users/ugrad/chungmop/eecs22/hw4/hw3_solution/PhotoLabTest)
==10393== 
==10393== LEAK SUMMARY:
==10393==    definitely lost: 8,843,489 bytes in 60 blocks
==10393==    indirectly lost: 589,824 bytes in 4 blocks
==10393==      possibly lost: 0 bytes in 0 blocks
==10393==    still reachable: 0 bytes in 0 blocks
==10393==         suppressed: 0 bytes in 0 blocks
==10393== 
==10393== For counts of detected and suppressed errors, rerun with: -v
==10393== Use --track-origins=yes to see where uninitialised values come from
==10393== ERROR SUMMARY: 2321235 errors from 86 contexts (suppressed: 4 from 4)
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm negative.ppm colorfilter.ppm edge.ppm vflip.ppm shuffle.ppm vmirror.ppm border.ppm noise.ppm sharpen.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
]0;chungmop@zuma:hw3_solution[chungmop@zuma hw3_solution]$ exit
exit

Script done on 西元2022年02月23日 (週三) 06時02分12秒
