Script started on 西元2022年03月11日 (週五) 08時46分44秒
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ make
gcc -Wall -std=c11 -c MovieLab.c -o MovieLab.o 
gcc -Wall -std=c11 -c FileIO.c -o FileIO.o 
gcc -Wall -std=c11 -c Movie.c -o Movie.o
gcc -Wall -std=c11 -c DIPs.c -o DIPs.o
gcc -Wall -std=c11   -c -o ImageList.o ImageList.c
gcc -Wall -std=c11 -c Image.c -o Image.o
gcc -Wall MovieLab.o Movie.o DIPs.o FileIO.o ImageList.o Image.o -lm -o MovieLab
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -h

Usage: MovieLab -i <file> -o <file> -f <framenum> -s <WIDTHxHEIGHT> [options]
Options:
-aging                Activate the aging filter on every movie frame
-hflip                Activate horizontal flip on every movie frame
-edge                 Activate the edge filter on every movie frame
-crop <start-end>     Crop the movie frames from <start> to <end>
-fast <factor>        Fast forward the movie by <factor>
-reverse              Reverse the frame order of the input movie
-watermark <file>     Add a watermark from <file> to every movie frame
-spotlight            Spotlight the fade in and fade out
-zoom                 Zoom in and out the input movie
-h                    Display this usage information
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -aging
Operation Aging is done!
The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -aging[K[K[K[K[Khflip
Operation HFlip is done!
The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -hflip[K[K[K[K[Kedge
Operation Edge is done!
The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -edge[K[K[K[Kfast 3
Operation Fast Forward is done! New number of frames is 23.
The movie file out.yuv has been written successfully!
52 frames are written to the file out.yuv in total.
MovieLab: ImageList.c:45: DeleteImageList: Assertion `image' failed.
Abort (core dumped)
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -fast 3[K[K[K[K[Kcrop 10-20
Segmentation fault (core dumped)
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -crop 10-20[K[K[K[K[K[K[K[K[Kreverse
Operation Reverse is done!
The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
MovieLab: ImageList.c:45: DeleteImageList: Assertion `image' failed.
Abort (core dumped)
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -reverse[K[K[K[K[K[K[Kwatermark -watermark.ppm
Operation watermark is done!
The movie file out.yuv has been written successfully!
70 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288 -watermark -watermark.ppm[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kspotlight
Operation Spotlight is done! New number of frames is 110.
The movie file out.yuv has been written successfully!
110 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ valgrinf[Kg [Kd ./Movie Lab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288
==21321== Memcheck, a memory error detector
==21321== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==21321== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==21321== Command: ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x401226: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x4012AA: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x401302: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x40137A: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x40150E: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x4015D5: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x4016A2: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x401749: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== Conditional jump or move depends on uninitialised value(s)
==21321==    at 0x401924: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
MovieLab: MovieLab.c:442: SaveMovie: Assertion `movie' failed.
==21321== 
==21321== Process terminating with default action of signal 6 (SIGABRT)
==21321==    at 0x32E08324F5: raise (in /lib64/libc-2.12.so)
==21321==    by 0x32E0833CD4: abort (in /lib64/libc-2.12.so)
==21321==    by 0x32E082B66D: __assert_fail_base (in /lib64/libc-2.12.so)
==21321==    by 0x32E082B72F: __assert_fail (in /lib64/libc-2.12.so)
==21321==    by 0x401E40: SaveMovie (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321==    by 0x401A5B: main (in /users/ugrad/chungmop/eecs22/hw5/MovieLab)
==21321== 
==21321== HEAP SUMMARY:
==21321==     in use at exit: 0 bytes in 0 blocks
==21321==   total heap usage: 2 allocs, 2 frees, 164 bytes allocated
==21321== 
==21321== All heap blocks were freed -- no leaks are possible
==21321== 
==21321== For counts of detected and suppressed errors, rerun with: -v
==21321== Use --track-origins=yes to see where uninitialised values come from
==21321== ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 4 from 4)
Abort (core dumped)
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ valgrind ./MovieLab -i EngPlaza.yuv -o out.yuv -f 70 -s 512x288[22G[9P[76G -spotlight[K[K[K[K[K[K[K[K[Kzoom
Operation Zoom is done!
The movie file out.yuv has been written successfully!
110 frames are written to the file out.yuv in total.
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ make clean
rm -f *.o
rm MovieLab
]0;chungmop@zuma:hw5[chungmop@zuma hw5]$ exit
exit

Script done on 西元2022年03月11日 (週五) 08時49分42秒
